import type { LlmError, Result } from "./types";
import { err, ok } from "./types";

const GEMINI_MODEL = "gemini-3-flash-preview";
const GEMINI_API_URL = `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent`;

export async function generateSocialDraft(
  apiKey: string,
  prompt: string
): Promise<Result<string, LlmError>> {
  let response: Response;
  try {
    response = await fetch(`${GEMINI_API_URL}?key=${apiKey}`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      signal: AbortSignal.timeout(60_000),
      body: JSON.stringify({
        contents: [{ parts: [{ text: prompt }] }],
        generationConfig: {
          temperature: 0.7,
          maxOutputTokens: 8192,
        },
      }),
    });
  } catch (error) {
    if (error instanceof DOMException && error.name === "TimeoutError") {
      return err({ kind: "timeout", message: "Gemini API request timed out" });
    }
    throw error;
  }

  if (!response.ok) {
    const text = await response.text();
    const message = `Gemini API error: ${response.status} ${response.statusText}\n${text}`;
    const kind = response.status >= 500 ? "server" : "client";
    return err({ kind, message, status: response.status } as LlmError);
  }

  const data = await response.json();
  const generatedText = data?.candidates?.[0]?.content?.parts?.[0]?.text;

  if (!generatedText) {
    return err({ kind: "no-content", message: "No text generated by Gemini API." });
  }

  return ok(generatedText.trim());
}
