import { LlmApiError } from "./llm-error";

const GITHUB_MODELS_MODEL = "gpt-4o";
const GITHUB_MODELS_URL = "https://models.github.com/chat/completions";

export async function generateSocialDraft(token: string, prompt: string): Promise<string> {
  const response = await fetch(GITHUB_MODELS_URL, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${token}`,
    },
    body: JSON.stringify({
      model: GITHUB_MODELS_MODEL,
      messages: [{ role: "user", content: prompt }],
      temperature: 0.7,
      max_tokens: 8192,
    }),
  });

  if (!response.ok) {
    const text = await response.text();
    throw new LlmApiError(
      `GitHub Models API error: ${response.status} ${response.statusText}\n${text}`,
      response.status
    );
  }

  const data = await response.json();
  const generatedText = data?.choices?.[0]?.message?.content;

  if (!generatedText) {
    throw new Error("No text generated by GitHub Models API.");
  }

  return generatedText.trim();
}
