import { approveAll, CopilotClient } from "@github/copilot-sdk";

import type { LlmError, Result } from "./types";
import { err, ok } from "./types";

const MODEL = "gpt-4.1";
const TIMEOUT_MS = 120_000;

export async function generateSocialDraft(
  token: string | undefined,
  prompt: string
): Promise<Result<string, LlmError>> {
  const client = new CopilotClient(token ? { githubToken: token } : { useLoggedInUser: true });

  try {
    await client.start();

    const authStatus = await client.getAuthStatus();
    if (!authStatus.isAuthenticated) {
      return err({
        kind: "auth",
        message:
          `GitHub Copilot SDK: ${authStatus.statusMessage ?? "Not authenticated"}. ` +
          "Set GITHUB_TOKEN or authenticate via 'gh auth login'.",
        status: 401,
      });
    }

    const session = await client.createSession({
      model: MODEL,
      onPermissionRequest: approveAll,
      systemMessage: {
        mode: "replace",
        content:
          "You are a social media copywriter. Respond only with the requested text. Do not use any tools, read files, or run commands.",
      },
    });

    try {
      const response = await session.sendAndWait({ prompt }, TIMEOUT_MS);
      const generatedText = response?.data?.content;

      if (!generatedText) {
        return err({ kind: "no-content", message: "No text generated by GitHub Copilot SDK." });
      }

      return ok(generatedText.trim());
    } finally {
      await session.disconnect();
    }
  } catch (error) {
    const isTimeout =
      (error instanceof DOMException && error.name === "TimeoutError") ||
      (error instanceof Error && error.message.toLowerCase().includes("timeout"));
    if (isTimeout) {
      return err({ kind: "timeout", message: "GitHub Copilot SDK timed out" });
    }

    const errObj = error as { status?: unknown; statusCode?: unknown };
    const status = errObj?.status ?? errObj?.statusCode ?? 500;
    return err({
      kind: "server",
      message: `GitHub Copilot SDK error: ${(error as Error).message}`,
      status: typeof status === "number" ? status : 500,
    });
  } finally {
    await client.stop();
  }
}
