import { CopilotClient, approveAll } from "@github/copilot-sdk";
import { LlmApiError } from "./llm-error";

const MODEL = "gpt-4o";

export async function generateSocialDraft(token: string, prompt: string): Promise<string> {
  const client = new CopilotClient({ githubToken: token });

  try {
    await client.start();
    const session = await client.createSession({
      model: MODEL,
      onPermissionRequest: approveAll,
    });

    try {
      const response = await session.sendAndWait({ prompt }, 60_000);
      const generatedText = response?.data?.content;

      if (!generatedText) {
        throw new Error("No text generated by GitHub Copilot SDK.");
      }

      return generatedText.trim();
    } finally {
      await session.disconnect();
    }
  } catch (error) {
    // Re-throw our own errors
    if (error instanceof LlmApiError) throw error;
    if (error instanceof Error && error.message === "No text generated by GitHub Copilot SDK.") throw error;

    // Map timeout errors to preserve fallback behavior in llm.ts
    const isTimeout =
      (error instanceof DOMException && error.name === "TimeoutError") ||
      (error instanceof Error && error.message.toLowerCase().includes("timeout"));
    if (isTimeout) {
      throw new DOMException("GitHub Copilot SDK timed out", "TimeoutError");
    }

    // Map other errors to LlmApiError for fallback compatibility
    const status = (error as any)?.status ?? (error as any)?.statusCode ?? 500;
    throw new LlmApiError(
      `GitHub Copilot SDK error: ${(error as Error).message}`,
      typeof status === "number" ? status : 500
    );
  } finally {
    await client.stop();
  }
}
